<a href="https://colab.research.google.com/github/NANDYALASAIVENKATAMANIVARMA/FML/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [7]:
data=pd.read_csv("/content/drive/MyDrive/Iris.csv")

In [8]:
iris=load_iris()

In [9]:
iris.data[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [11]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [14]:
print(type(iris.data))


<class 'numpy.ndarray'>


In [15]:
print(type(iris.target))
     

<class 'numpy.ndarray'>


In [16]:
iris.data.shape

(150, 4)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=51)

In [19]:
X_train.shape, X_test.shape

((90, 4), (60, 4))

In [20]:
y_train.shape, y_train.shape

((90,), (90,))

In [23]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [24]:
y_pred = knn.predict(X_test)
     

In [25]:
knn.score(X_train, y_train), knn.score(X_test, y_test)
     

(0.9777777777777777, 0.9166666666666666)

In [26]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(knn.score(X_train, y_train), knn.score(X_test, y_test))

0.9666666666666667 0.9333333333333333


In [27]:
confusion_matrix(y_test, y_pred)

array([[15,  0,  0],
       [ 0, 25,  0],
       [ 0,  4, 16]])

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.86      1.00      0.93        25
           2       1.00      0.80      0.89        20

    accuracy                           0.93        60
   macro avg       0.95      0.93      0.94        60
weighted avg       0.94      0.93      0.93        60

